// <auto-generated />
using System;
using Carsharing.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carsharing.DataAccess.Migrations
{
    [DbContext(typeof(CarsharingDbContext))]
    [Migration("20260422134236_UpdateModels")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BillEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bill_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasColumnName("bill_amount");

                    b.Property<DateTime>("IssueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bill_issue_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("PromocodeId")
                        .HasColumnType("integer")
                        .HasColumnName("bill_promocode_id");

                    b.Property<decimal?>("RemainingAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasColumnName("bill_remaining_amount");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("bill_status_id");

                    b.Property<int>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("bill_trip_id");

                    b.HasKey("Id");

                    b.HasIndex("PromocodeId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TripId")
                        .IsUnique();

                    b.ToTable("bills", null, t =>
                        {
                            t.HasCheckConstraint("bills_bill_remaining_amount_check", "bill_remaining_amount >= 0");

                            t.HasCheckConstraint("chk_bill_amount_nonneg", "bill_amount IS NULL OR bill_amount >= 0");
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BillStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("bill_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Не оплачен"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Частично оплачен"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Оплачен"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Отменён"
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BookingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_car_id");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_client_id");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booking_end_time");

                    b.Property<DateTime?>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booking_start_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_status_id");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.HasIndex("StatusId");

                    b.ToTable("bookings", null, t =>
                        {
                            t.HasCheckConstraint("chk_booking_times", "booking_start_time IS NULL OR booking_end_time IS NULL OR booking_start_time < booking_end_time");
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BookingStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("booking_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Активно"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Завершено"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Отменено"
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.CarEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("car_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("car_category_id");

                    b.Property<Point>("Coordinates")
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("car_coordinates");

                    b.Property<decimal>("FuelLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("car_fuel_level");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("car_image_path");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("car_location");

                    b.Property<int>("SpecificationId")
                        .HasColumnType("integer")
                        .HasColumnName("car_specification_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("car_status_id");

                    b.Property<int>("TariffId")
                        .HasColumnType("integer")
                        .HasColumnName("car_tariff_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SpecificationId")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.HasIndex("TariffId");

                    b.ToTable("cars", null, t =>
                        {
                            t.HasCheckConstraint("chk_fuel_level", "car_fuel_level >= 0");
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.CarStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("car_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Доступна"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Недоступен"
                        },
                        new
                        {
                            Id = 3,
                            Name = "На обслуживании"
                        },
                        new
                        {
                            Id = 4,
                            Name = "В ремонте"
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_name");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.ClientDocumentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("document_client_id");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("document_expiry_date");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("document_file_path");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("document_issue_date");

                    b.Property<string>("LicenseCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_license_category");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("client_documents", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.ClientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_phone_number");

                    b.Property<string>("Surname")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_surname");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("client_user_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("clients", null, t =>
                        {
                            t.HasCheckConstraint("chk_client_email_format", "client_email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'");
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.FavoritesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.ToTable("favorite_cars", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.FineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("fine_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("fine_amount");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fine_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("fine_status_id");

                    b.Property<int>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("fine_trip_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fine_type");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TripId");

                    b.ToTable("fines", null, t =>
                        {
                            t.HasCheckConstraint("chk_fine_amount_nonneg", "fine_amount >= 0");
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.FineStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("fine_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Начислен"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ожидает оплаты"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Оплачен"
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.InsuranceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("insurance_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer")
                        .HasColumnName("insurance_car_id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("insurance_company");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("insurance_cost");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("insurance_end_date");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("insurance_policy_number");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("insurance_start_date");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("insurance_status_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("insurance_type");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("insurance", null, t =>
                        {
                            t.HasCheckConstraint("chk_insurance_dates", "insurance_start_date IS NULL OR insurance_end_date IS NULL OR insurance_start_date <= insurance_end_date");
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.InsuranceStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("insurance_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Активна"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Истекла"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Аннулирована"
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.MaintenanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("maintenance_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer")
                        .HasColumnName("maintenance_car_id");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("maintenance_cost");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("maintenance_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("maintenance_description");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("maintenance_work_type");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("maintenance", null, t =>
                        {
                            t.HasCheckConstraint("chk_maintenance_cost_nonneg", "maintenance_cost IS NULL OR maintenance_cost >= 0");
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.PaymentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_bill_id");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Method")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Картой")
                        .HasColumnName("payment_method");

                    b.Property<decimal>("Sum")
                        .HasColumnType("numeric")
                        .HasColumnName("payment_sum");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.PromocodeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("promocode_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("promocode_code");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("promocode_discount");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("promocode_end_date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("promocode_start_date");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("promocode_status_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("promocodes", null, t =>
                        {
                            t.HasCheckConstraint("chk_promocode_dates", "promocode_start_date IS NULL OR promocode_end_date IS NULL OR promocode_start_date <= promocode_end_date");
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.PromocodeStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("promocode_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Активен"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Истёк"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Использован"
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.ReviewEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("review_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer")
                        .HasColumnName("review_car_id");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("review_client_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("review_comment");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("review_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("review_rating");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("reviews_review_rating_check", "review_rating >= 1 AND review_rating <= 5");
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Администратор"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Клиент"
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.SpecificationCarEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("specification_car_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("specification_car_brand");

                    b.Property<decimal>("FuelPerKm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0.08m)
                        .HasColumnName("specification_fuel_per_km");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("specification_car_fuel_type");

                    b.Property<decimal>("MaxFuel")
                        .HasColumnType("numeric")
                        .HasColumnName("specification_car_max_fuel");

                    b.Property<int>("Mileage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("specification_car_mileage");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specification_car_model");

                    b.Property<string>("StateNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("specification_car_state_number");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("specification_car_transmission");

                    b.Property<string>("VinNumber")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("specification_car_vin_number");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("specification_car_year");

                    b.HasKey("Id");

                    b.HasIndex("StateNumber")
                        .IsUnique();

                    b.HasIndex("VinNumber")
                        .IsUnique();

                    b.ToTable("specifications_car", null, t =>
                        {
                            t.HasCheckConstraint("chk_specification_car_max_fuel_positive", "specification_car_max_fuel >= 0");

                            t.HasCheckConstraint("chk_specification_car_mileage_non_negative", "specification_car_mileage >= 0");

                            t.HasCheckConstraint("chk_specification_car_year_range", "specification_car_year >= 1900 AND specification_car_year <= EXTRACT(year FROM CURRENT_DATE) + 1");

                            t.HasCheckConstraint("specifications_car_specification_fuel_per_km_check", "specification_fuel_per_km >= 0");
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TariffEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tariff_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tariff_name");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("numeric")
                        .HasColumnName("tariff_price_per_day");

                    b.Property<decimal>("PricePerKm")
                        .HasColumnType("numeric")
                        .HasColumnName("tariff_price_per_km");

                    b.Property<decimal>("PricePerMinute")
                        .HasColumnType("numeric")
                        .HasColumnName("tariff_price_per_minute");

                    b.HasKey("Id");

                    b.ToTable("tariffs", null, t =>
                        {
                            t.HasCheckConstraint("chk_tariff_prices_nonneg", "COALESCE(tariff_price_per_minute, 0) >= 0 AND COALESCE(tariff_price_per_km, 0) >= 0 AND COALESCE(tariff_price_per_day, 0) >= 0");
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TripDetailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("trip_detail_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trip_detail_end_location");

                    b.Property<decimal?>("FuelUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("trip_detail_fuel_used");

                    b.Property<bool>("InsuranceActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("trip_detail_insurance_active");

                    b.Property<decimal?>("Refueled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("trip_detail_refueled");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trip_detail_start_location");

                    b.Property<int>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("trip_detail_trip_id");

                    b.HasKey("Id");

                    b.HasIndex("TripId")
                        .IsUnique();

                    b.ToTable("trip_details", null, t =>
                        {
                            t.HasCheckConstraint("chk_trip_detail_fuel_used_nonneg", "trip_detail_fuel_used IS NULL OR trip_detail_fuel_used >= 0");

                            t.HasCheckConstraint("chk_trip_detail_refueled_nonneg", "trip_detail_refueled IS NULL OR trip_detail_refueled >= 0");
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TripEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("trip_booking_id");

                    b.Property<decimal?>("Distance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("trip_distance_km");

                    b.Property<decimal?>("Duration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("trip_duration");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trip_end_time");

                    b.Property<DateTime>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trip_start_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("trip_status_id");

                    b.Property<string>("TariffType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trip_tariff_type");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("trips", null, t =>
                        {
                            t.HasCheckConstraint("chk_trip_distance_nonneg", "trip_distance_km IS NULL OR trip_distance_km >= 0");

                            t.HasCheckConstraint("chk_trip_duration_nonneg", "trip_duration IS NULL OR trip_duration >= 0");

                            t.HasCheckConstraint("chk_trip_times", "trip_start_time IS NULL OR trip_end_time IS NULL OR trip_start_time <= trip_end_time");
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TripStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("trip_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ожидание начала"
                        },
                        new
                        {
                            Id = 2,
                            Name = "В пути"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Завершена"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Отменена системой"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Требуется оплата"
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_password_hash");

                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("user_role_id");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BillEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.PromocodeEntity", "Promocode")
                        .WithMany("Bill")
                        .HasForeignKey("PromocodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Carsharing.DataAccess.Entites.BillStatusEntity", "BillStatus")
                        .WithMany("Bills")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.TripEntity", "Trip")
                        .WithOne("Bill")
                        .HasForeignKey("Carsharing.DataAccess.Entites.BillEntity", "TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillStatus");

                    b.Navigation("Promocode");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BookingEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.CarEntity", "Car")
                        .WithMany("Booking")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.ClientEntity", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.BookingStatusEntity", "BookingStatus")
                        .WithMany("Bookings")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookingStatus");

                    b.Navigation("Car");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.CarEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.CategoryEntity", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.SpecificationCarEntity", "SpecificationCar")
                        .WithOne("Car")
                        .HasForeignKey("Carsharing.DataAccess.Entites.CarEntity", "SpecificationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.CarStatusEntity", "CarStatus")
                        .WithMany("Cars")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.TariffEntity", "Tariff")
                        .WithMany("Cars")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarStatus");

                    b.Navigation("Category");

                    b.Navigation("SpecificationCar");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.ClientDocumentEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.ClientEntity", "Client")
                        .WithMany("Documents")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.ClientEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.UserEntity", "User")
                        .WithOne("Client")
                        .HasForeignKey("Carsharing.DataAccess.Entites.ClientEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.FavoritesEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.CarEntity", "Car")
                        .WithMany("Favorites")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.ClientEntity", "Client")
                        .WithMany("Favorites")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.FineEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.FineStatusEntity", "FineStatus")
                        .WithMany("Fines")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.TripEntity", "Trip")
                        .WithMany("Fine")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FineStatus");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.InsuranceEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.CarEntity", "Car")
                        .WithMany("Insurance")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.InsuranceStatusEntity", "InsuranceStatus")
                        .WithMany("Insurances")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("InsuranceStatus");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.MaintenanceEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.CarEntity", "Car")
                        .WithMany("Maintenance")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.PaymentEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.BillEntity", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.PromocodeEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.PromocodeStatusEntity", "PromocodeStatus")
                        .WithMany("Promocodes")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PromocodeStatus");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.ReviewEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.CarEntity", "Car")
                        .WithMany("Reviews")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.ClientEntity", "Client")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TripDetailEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.TripEntity", "Trip")
                        .WithOne("TripDetail")
                        .HasForeignKey("Carsharing.DataAccess.Entites.TripDetailEntity", "TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TripEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.BookingEntity", "Booking")
                        .WithOne("Trip")
                        .HasForeignKey("Carsharing.DataAccess.Entites.TripEntity", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.TripStatusEntity", "TripStatus")
                        .WithMany("Trip")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("TripStatus");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.UserEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.RoleEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BillEntity", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BillStatusEntity", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BookingEntity", b =>
                {
                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BookingStatusEntity", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.CarEntity", b =>
                {
                    b.Navigation("Booking");

                    b.Navigation("Favorites");

                    b.Navigation("Insurance");

                    b.Navigation("Maintenance");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.CarStatusEntity", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.CategoryEntity", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.ClientEntity", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Documents");

                    b.Navigation("Favorites");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.FineStatusEntity", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.InsuranceStatusEntity", b =>
                {
                    b.Navigation("Insurances");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.PromocodeEntity", b =>
                {
                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.PromocodeStatusEntity", b =>
                {
                    b.Navigation("Promocodes");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.RoleEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.SpecificationCarEntity", b =>
                {
                    b.Navigation("Car");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TariffEntity", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TripEntity", b =>
                {
                    b.Navigation("Bill");

                    b.Navigation("Fine");

                    b.Navigation("TripDetail");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TripStatusEntity", b =>
                {
                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.UserEntity", b =>
                {
                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
