// <auto-generated />
using System;
using Carsharing.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carsharing.DataAccess.Migrations
{
    [DbContext(typeof(CarsharingDbContext))]
    partial class CarsharingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BillEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric");

                    b.Property<DateTime>("IssueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("PromocodeId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RemainingAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasColumnName("bill_remaining_amount");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PromocodeId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TripId")
                        .IsUnique();

                    b.ToTable("bills", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BillStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("bill_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 13,
                            Name = "Не оплачен"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Частично оплачен"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Оплачен"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Отменён"
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BookingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.HasIndex("StatusId");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BookingStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("booking_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Name = "Активно"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Завершено"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Отменено"
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.CarEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FuelLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SpecificationId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("TariffId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SpecificationId")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.HasIndex("TariffId");

                    b.ToTable("cars", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.CarStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("car_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Доступен"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Недоступен"
                        },
                        new
                        {
                            Id = 3,
                            Name = "На обслуживании"
                        },
                        new
                        {
                            Id = 4,
                            Name = "В ремонте"
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.ClientDocumentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("LicenseCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("client_documents", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.ClientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Surname")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.FavoritesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.ToTable("favorite_cars", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.FineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TripId");

                    b.ToTable("fines", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.FineStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("fine_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 17,
                            Name = "Начислен"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Ожидает оплаты"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Оплачен"
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.InsuranceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("insurances", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.InsuranceStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("insurance_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 23,
                            Name = "Активна"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Истекла"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Аннулирована"
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.MaintenanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("maintenances", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.PaymentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Method")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Картой");

                    b.Property<decimal>("Sum")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.PromocodeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("promocodes", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.PromocodeStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("promocode_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 20,
                            Name = "Активен"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Истек"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Использован"
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.ReviewEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.SpecificationCarEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("FuelPerKm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0.08m);

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxFuel")
                        .HasColumnType("numeric");

                    b.Property<int>("Mileage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StateNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VinNumber")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StateNumber")
                        .IsUnique();

                    b.HasIndex("VinNumber")
                        .IsUnique();

                    b.ToTable("specifications_car", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TariffEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PricePerKm")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PricePerMinute")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("tariffs", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TripDetailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("FuelUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<bool>("InsuranceActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("Refueled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TripId")
                        .IsUnique();

                    b.ToTable("trip_details", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TripEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Distance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("Duration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("TariffType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TripStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("trip_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 8,
                            Name = "Ожидание начала"
                        },
                        new
                        {
                            Id = 9,
                            Name = "В пути"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Завершена"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Отменена"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Требуется оплата"
                        });
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BillEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.PromocodeEntity", "Promocode")
                        .WithMany("Bill")
                        .HasForeignKey("PromocodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Carsharing.DataAccess.Entites.BillStatusEntity", "BillStatus")
                        .WithMany("Bills")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.TripEntity", "Trip")
                        .WithOne("Bill")
                        .HasForeignKey("Carsharing.DataAccess.Entites.BillEntity", "TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillStatus");

                    b.Navigation("Promocode");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BookingEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.CarEntity", "Car")
                        .WithMany("Booking")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.ClientEntity", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.BookingStatusEntity", "BookingStatus")
                        .WithMany("Bookings")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("BookingStatus");

                    b.Navigation("Car");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.CarEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.CategoryEntity", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.SpecificationCarEntity", "SpecificationCar")
                        .WithOne("Car")
                        .HasForeignKey("Carsharing.DataAccess.Entites.CarEntity", "SpecificationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.CarStatusEntity", "CarStatus")
                        .WithMany("Cars")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.TariffEntity", "Tariff")
                        .WithMany("Cars")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("CarStatus");

                    b.Navigation("Category");

                    b.Navigation("SpecificationCar");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.ClientDocumentEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.ClientEntity", "Client")
                        .WithMany("Documents")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.ClientEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.UserEntity", "User")
                        .WithOne("Client")
                        .HasForeignKey("Carsharing.DataAccess.Entites.ClientEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.FavoritesEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.CarEntity", "Car")
                        .WithMany("Favorites")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.ClientEntity", "Client")
                        .WithMany("Favorites")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.FineEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.FineStatusEntity", "FineStatus")
                        .WithMany("Fines")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.TripEntity", "Trip")
                        .WithMany("Fine")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FineStatus");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.InsuranceEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.CarEntity", "Car")
                        .WithMany("Insurance")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.InsuranceStatusEntity", "InsuranceStatus")
                        .WithMany("Insurances")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("InsuranceStatus");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.MaintenanceEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.CarEntity", "Car")
                        .WithMany("Maintenance")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.PaymentEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.BillEntity", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.PromocodeEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.PromocodeStatusEntity", "PromocodeStatus")
                        .WithMany("Promocodes")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("PromocodeStatus");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.ReviewEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.CarEntity", "Car")
                        .WithMany("Reviews")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.ClientEntity", "Client")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TripDetailEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.TripEntity", "Trip")
                        .WithOne("TripDetail")
                        .HasForeignKey("Carsharing.DataAccess.Entites.TripDetailEntity", "TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TripEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.BookingEntity", "Booking")
                        .WithOne("Trip")
                        .HasForeignKey("Carsharing.DataAccess.Entites.TripEntity", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carsharing.DataAccess.Entites.TripStatusEntity", "TripStatus")
                        .WithMany("Trip")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("TripStatus");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.UserEntity", b =>
                {
                    b.HasOne("Carsharing.DataAccess.Entites.RoleEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BillEntity", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BillStatusEntity", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BookingEntity", b =>
                {
                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.BookingStatusEntity", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.CarEntity", b =>
                {
                    b.Navigation("Booking");

                    b.Navigation("Favorites");

                    b.Navigation("Insurance");

                    b.Navigation("Maintenance");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.CarStatusEntity", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.CategoryEntity", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.ClientEntity", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Documents");

                    b.Navigation("Favorites");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.FineStatusEntity", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.InsuranceStatusEntity", b =>
                {
                    b.Navigation("Insurances");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.PromocodeEntity", b =>
                {
                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.PromocodeStatusEntity", b =>
                {
                    b.Navigation("Promocodes");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.RoleEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.SpecificationCarEntity", b =>
                {
                    b.Navigation("Car");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TariffEntity", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TripEntity", b =>
                {
                    b.Navigation("Bill");

                    b.Navigation("Fine");

                    b.Navigation("TripDetail");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.TripStatusEntity", b =>
                {
                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Carsharing.DataAccess.Entites.UserEntity", b =>
                {
                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
